name: NoExplosionDamage
version: 1.0.0
main: net.kchscraft.noexplosiondamage.NoExplosionDamage
description: Disables damage on player from explosions (End Crystal, TNT Minecart)
author: D3adhkwen
api-version: 1.13